services:
  tcg-downloader:
    build: .
    container_name: tcg-downloader
    tty: true
    stdin_open: true
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./data:/app/data
      - ./src:/app/src